flowchart LR
    A{Análisis} --> B[Costos]
    A --> C[Beneficios]
    
    B --> D[Hardware inicial]
    B --> E[Mantenimiento]
    B --> F[Energía]
    B --> G[Personal técnico]
    
    C --> H[Privacidad]
    C --> I[Control]
    C --> J[Ahorro a largo plazo]
    C --> K[Cumplimiento legal]
    
    style A fill:#ccffff
    style B fill:#ffcccc
    style C fill:#ccffcc